### ISSUE TITLE
代码崩了，不知道作者能修复下吗，急～

### ISSUE THREAD

**Issue by leaDongYang** [chihaodong/RMCalendar#1]
wCurMonth   计算农历天干，地支，月，日后，变成了乱码，然后造成数组越界蹦了，不知道作者是否还能修复下这个问题，感激不尽！

**Comment by chihaodong** [comment]
已经修复 重新下载下  就可以了

**Comment by leaDongYang** [comment]
感谢作者，太及时了，谢谢，不知道能否说下，崩溃原因啊，搞不懂呢
